name = "example_suite"
time_limit = 600
memory_limit = 3000

[[solvers]]
name = "lama"
attributes = "downward"
path = "solvers/fast_downward.sh"
args = ["lama"]

[[solvers]]
name = "lama-first"
attributes = "downward"
path = "solvers/fast_downward.sh"
args = ["lama-first"]

[[attributes]]
name = "downward"
patterns = [
    { name = "total_time", pattern = "Total time: ([0-9.]*)" },
    { name = "search_time", pattern = "Search time: ([0-9.]*)" },
]

[[tasks]]
name = "blocksworld"
domain = "blocksworld/domain.pddl"
problems_training = "blocksworld/problem.pddl"
problems_testing = "blocksworld/problem.pddl"
