time_limit_learn = 600    # seconds
memory_limit_learn = 3000 # mb
time_limit_solve = 600    # seconds
memory_limit_solve = 3000 # mb

[[runners]]
name = "lama"
attributes = "downward"
path = "solvers/fast_downward.sh"
args = ["lama"]
kind = "Solve"

[[runners]]
name = "lama-first"
attributes = "downward"
path = "solvers/fast_downward.sh"
args = ["lama-first"]
kind = "Solve"

[[attributes]]
name = "downward"
patterns = [
    { name = "total_time", pattern = "Total time: ([0-9.]*)" },
    { name = "search_time", pattern = "Search time: ([0-9.]*)" },
]

[[tasks]]
name = "blocksworld"
domain = "blocksworld/domain.pddl"
solve = "blocksworld/problem.pddl"
